typography_spectrum: 0.6973706898279488
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.43037726846523583
  lightness: 0.8377044978551567
  saturation: 0.7098571388050914
  rhythmicContrast: 0.9003591081127524
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2924831514246762
analytics:
  google: null
  facebook: null
  twitter: null
name: Travel-Media-EU
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'Unsere Erfahrung '
    id: a58dda91-e64c-4fd8-8902-ce3795d10950
    type: content
  - name: Unsere Services
    id: 7c32dc3a-5b8b-4a89-90bf-b2fa05f749f5
    type: content
favicon: null
purpose: []
