typography_spectrum: 0.08953262655995786
color:
  brandColors:
    - '#FFFFFF'
    - '#5F5E5D'
    - '#2F9CD4'
    - '#FF8E01'
    - '#80D11C'
  brandStrength: 0.12183423084206879
  lightness: 0.5505159413442016
  saturation: 0.667364269727841
  rhythmicContrast: 0.6233720418531448
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.05979795171879232
analytics:
  google: null
  facebook: null
  twitter: null
name: Travel-Media-EU
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Unsere Services
    id: 7c32dc3a-5b8b-4a89-90bf-b2fa05f749f5
    type: content
  - name: Unsere Erfahrung
    id: fb504c79-ff41-4057-bf7b-6abaaf410219
    type: content
  - name: Impressum
    id: 35da97c9-4b79-4ddf-9075-e1cccdfcf28c
    type: content
favicon: null
title: Internet Marketing
description: speziell fürs Reisegeschäft!
purpose: []
