typography_spectrum: 0.12725332169793546
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.22717278683558106
  lightness: 0.686409906251356
  saturation: 0.8791352675762028
  rhythmicContrast: 0.9952573738992214
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.12763318745419383
analytics:
  google: null
  facebook: null
  twitter: null
name: Travel-Media-EU
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Unsere Services
    id: 7c32dc3a-5b8b-4a89-90bf-b2fa05f749f5
    type: content
  - name: Unsere Erfahrung ist der Grundstein Ihres Erfolges
    id: fb504c79-ff41-4057-bf7b-6abaaf410219
    type: content
favicon: null
title: Internet Marketing
description: speziell fürs Reisegeschäft!
purpose: []
