name: Travel-Media-EU
favicon: null
layout_spectrum: 0.2924831514246762
typography_spectrum: 0.6973706898279488
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.43037726846523583
  lightness: 0.8377044978551567
  saturation: 0.7098571388050914
  rhythmicContrast: 0.9003591081127524
purpose: []
